# Generated by Django 6.0.5 on 2026-05-27 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_tasks', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSelectedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_tasks', to='rooms.room')),
                ('selected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_selected_tasks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_in_rooms', to='coding_tasks.codingtask')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['room', 'position', 'created_at'], name='rooms_rooms_room_id_0167d8_idx')],
                'constraints': [models.UniqueConstraint(fields=('room', 'task'), name='unique_room_selected_task')],
            },
        ),
    ]
