# Generated by Django 6.0.5 on 2026-06-12 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomchatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='round_count',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
