# Generated by Django 6.0.5 on 2026-05-25 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coding_tasks', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Runtime Error', 'Runtime Error'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Compilation Error', 'Compilation Error')], max_length=32)),
                ('execution_time', models.FloatField(default=0)),
                ('test_results', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('manual_decision', models.CharField(blank=True, choices=[('', 'None'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='', max_length=16)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='matches.match')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_submissions', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='matches.round')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='coding_tasks.codingtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['match', 'round', 'user'], name='submissions_match_i_36d32b_idx'), models.Index(fields=['status'], name='submissions_status_c2b4f2_idx'), models.Index(fields=['submitted_at'], name='submissions_submitt_f62c88_idx')],
            },
        ),
    ]
