# Generated by Django 6.0.5 on 2026-05-25 05:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('visible_tests', models.JSONField(blank=True, default=list)),
                ('hidden_tests', models.JSONField(blank=True, default=list)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=16)),
                ('time_limit', models.FloatField(default=2.0, help_text='Seconds per test case.', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('memory_limit', models.PositiveIntegerField(default=128, help_text='Megabytes.', validators=[django.core.validators.MinValueValidator(16)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coding_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['difficulty', '-created_at'],
                'indexes': [models.Index(fields=['difficulty'], name='coding_task_difficu_2efa6e_idx'), models.Index(fields=['created_at'], name='coding_task_created_c71efe_idx')],
            },
        ),
    ]
