# Generated by Django 6.0.5 on 2026-05-25 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0)),
                ('solved_count', models.PositiveIntegerField(default=0)),
                ('total_solution_time', models.FloatField(default=0)),
                ('player_status', models.CharField(choices=[('active', 'Active'), ('eliminated', 'Eliminated'), ('winner', 'Winner'), ('left', 'Left')], default='active', max_length=16)),
                ('eliminated', models.BooleanField(default=False)),
                ('last_submission_status', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='matches.match')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points', 'total_solution_time', 'updated_at'],
                'indexes': [models.Index(fields=['room', 'match'], name='leaderboard_room_id_653908_idx'), models.Index(fields=['player_status'], name='leaderboard_player__e12919_idx')],
                'constraints': [models.UniqueConstraint(fields=('match', 'user'), name='unique_leaderboard_entry')],
            },
        ),
    ]
