# Generated by Django 6.0.5 on 2026-05-25 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coding_tasks', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('finished', 'Finished')], default='waiting', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='rooms.room')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('eliminated', 'Eliminated'), ('winner', 'Winner'), ('left', 'Left')], default='active', max_length=16)),
                ('score', models.PositiveIntegerField(default=0)),
                ('solved_rounds', models.PositiveIntegerField(default=0)),
                ('total_solution_time', models.FloatField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('eliminated_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'total_solution_time', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('finished', 'Finished')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='matches.match')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rounds', to='coding_tasks.codingtask')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='current_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='matches.round'),
        ),
        migrations.CreateModel(
            name='RoundParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('solved', 'Solved'), ('passed', 'Passed'), ('eliminated', 'Eliminated')], default='active', max_length=16)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.FloatField(default=0)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_states', to='matches.matchparticipant')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_participants', to='matches.round')),
            ],
        ),
        migrations.AddIndex(
            model_name='matchparticipant',
            index=models.Index(fields=['match', 'status'], name='matches_mat_match_i_957134_idx'),
        ),
        migrations.AddIndex(
            model_name='matchparticipant',
            index=models.Index(fields=['user', 'status'], name='matches_mat_user_id_141ac7_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchparticipant',
            constraint=models.UniqueConstraint(fields=('match', 'user'), name='unique_match_participant'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('match', 'number'), name='unique_round_number_per_match'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['room', 'status'], name='matches_mat_room_id_013fee_idx'),
        ),
        migrations.AddIndex(
            model_name='roundparticipant',
            index=models.Index(fields=['round', 'status'], name='matches_rou_round_i_c89701_idx'),
        ),
        migrations.AddConstraint(
            model_name='roundparticipant',
            constraint=models.UniqueConstraint(fields=('round', 'participant'), name='unique_round_participant'),
        ),
    ]
